### ISSUE TITLE
A question about bounds checking

### ISSUE THREAD

**Issue by qdwang** [Shnatsel/bounds-check-cookbook#1]
This cookbook is amazingly good and I've learned a lot from it. 
But still I cannot figure out how to avoid bounds checking for this code:

```rust
fn get_avg(image: &[u8], i: usize, w: usize) -> u8 {
    let a = image[i - w] as u16;
    let b = image[i + w] as u16;
    let c = image[i - 1] as u16;
    let d = image[i + 1] as u16;
    (a + b + c + d) / 4
}
```

All the indexes are calculated, `i` is the current index and `w` is the width of the image.

**Comment by Shnatsel** [comment]
I assume this is called in a loop. The key is rewriting the loop using iterators:

```rust
pub fn average_pixels(input: &[u8], width: usize, output: &mut [u8]) {
    assert!(input.len() == output.len());

    // set up iterators over rows so we could look up and down
    let previous_rows = input.chunks_exact(width);
    let current_rows = input.chunks_exact(width).skip(1);
    let next_rows = input.chunks_exact(width).skip(2);
    let output_rows = output.chunks_exact_mut(width).skip(1);
    
    // loop over rows
    previous_rows.zip(current_rows).zip(next_rows).zip(output_rows)
        .for_each(|(((previous_row, current_row), next_row), output_row)| {
            
            // set up iterators over pixels, horizontally
            let prev_row_pixels = previous_row.iter().skip(1);
            let next_row_pixels = next_row.iter().skip(1);
            let output_pixel = output_row.iter_mut().skip(1);
            // more succinct than 3 iterators over previous, current and next pixel horizontally
            let horizontal_windows = current_row.windows(3);

            // loop over pixels
            prev_row_pixels.zip(next_row_pixels).zip(output_pixel).zip(horizontal_windows)
            .for_each(|(((prev_row_pixel, next_row_pixel), output_pixel), window)| {
                let prev_pixel = window[0];
                // let current_pixel = window[1]; // never used
                let next_pixel = window[2];
                *output_pixel = ((prev_pixel as u16) + (next_pixel as u16) + (*prev_row_pixel as u16) + (*next_row_pixel as u16) / 4) as u8;
            })
        })
}
```

This involves a lot of boilerplate but does get rid of bounds checks.

Assembly view showing no bounds checks: https://godbolt.org/z/6sed55Y3a

**Comment by Shnatsel** [comment]
You really should benchmark this though. Deeply nested iterators often result in poor codegen. This produces quite a lot of assembly, it might be slower than the version with bounds checks.

Alternatively, asserts to constrain `w` could work instead of converting the whole thing to iterators. They need to be done at the start of the loop.

**Comment by qdwang** [comment]
Thanks very much for the reply.

** Deeply nested iterators often result in poor codegen **, I agree. I benchmarked complex iterator combination(3 zips) version vs index accessing version before. The iterator version is slower. So I think I'll still use index accessing.
